### ISSUE TITLE
Épico: Adaptar telas antigas para novas telas de railsui

### ISSUE THREAD

**Issue by eskokado** [eskokado/startup-delivery#142]
- [ ] HU: Admin QUERO adaptar telas de gestão de produtos
- [ ] HU: Admin QUERO adaptar telas de gestão de adicionais
- [ ] HU: Admin QUERO adaptar telas de gestão de sabores
- [ ] HU: Admin QUERO adaptar telas de gestão de pedidos
- [ ] HU: Admin QUERO adaptar telas de gestão de categorias
- [ ] HU: Admin QUERO adaptar telas de gestão de locais de entregas
- [ ] HU: Admin QUERO adaptar telas de gestão de balconista
- [ ] HU: Admin QUERO adaptar tela de dashboard
